### ISSUE TITLE
Build instructions are not correct.

### ISSUE THREAD

**Issue by henri62** [devolo/dlan-greenphy-sdk#15]
If you literally follow the build instructions (In Usage) it won't build. Probably the "compiler setup" part whatever is not documented? (For example the FirmwareStandalone or whatever)

16:05:57 **** Incremental Build of configuration Default for project dlan-greenphy-sdk ****
make all 
make: *** No rule to make target 'all'.  Stop.
"make all" terminated with exit code 2. Build might be incomplete.

16:05:57 Build Failed. 1 errors, 0 warnings. (took 420ms)

Used version:
MCUXpresso IDE v11.3.1 [Build 5262] [2021-04-02]

**Comment by Molkenbur** [comment]
You might be right. To make sure, that the instructions are working as described, please use: MCUXpresso IDE v11.1.0. There was already a hint in the Requirements section. Unfortunately, we have no better solution in place.
