### ISSUE TITLE
How to use dlan-greenphy-sdk to develop QCA7005

### ISSUE THREAD

**Issue by 1tianmaxingkong1** [devolo/dlan-greenphy-sdk#16]
We want to use dlan-greenphy-sdk to realize the complete process of DC fast charging, what should we do, and look forward to your reply.

**Comment by Molkenbur** [comment]
Hi 1tianmaxingkong1,
I am not able to understand your question completely.
But the LPC processor on the GreenPhy module, which is connected to the Evalboard, might not be powerful enough for a complete DC fast charging implementation. I guess, you have another CPU running your software and that you want to connect the GreenPhy Module via Ethernet.

**Comment by 1tianmaxingkong1** [comment]
Nice to receive your reply.
What I mean is that if I have an Evalboard, we want to realize the function of DC fast charging, how do we learn to achieve the goal of DC fast charging?

At the same time, I would like to ask whether the firmware of QCA7005 is included in the development kit of Evalboard, and can this firmware be directly used for charging products?

**Comment by Molkenbur** [comment]
To be honest, fast DC charging is much more than the communication with the electric vehicle via PLC and we cannot support you with the implementation of DC charging.
Regarding the QCA7005. As far as I know, you can use the firmware artifacts from the SDK to update the flash of the GreenPhy chip QCA7005. Even if our GreenPhy module has a QCA7000. But no guarantee for that.
And yes, this firmware can be used for DC chargers. But you have to add protocols running on your own CPU.

**Comment by China-Caden** [comment]
Do you have a QCA7000 driver for Linux 4.1.15?
All the drivers I found were Linux version 2.36 on imx28 board, and I don't know how to implement it.

**Comment by Molkenbur** [comment]
To be honest, I cannot help. We do not develop or have Linux drivers.

**Comment by China-Caden** [comment]
Hahhha, Just today, I have successfully ported the driver to imx6ull chip to run.
Thank you and best wishes.



欧志广
 
手机：15622924323
***@***.*** 
官网：www.wattsaving.com

深圳市能效电气技术有限公司 
公司地址：深圳市宝安区兴业路3012号老兵大厦西座(三)-3楼
工厂地址：深圳市宝安区西乡茶西经发工业园A栋1—3楼

能效电气 绿色未来
WattSaving For Future 
 
From: Molkenbur
Date: 2022-03-07 16:09
To: devolo/dlan-greenphy-sdk
CC: China-Caden; Comment
Subject: Re: [devolo/dlan-greenphy-sdk] How to use dlan-greenphy-sdk to develop QCA7005 (Issue #16)
To be honest, I cannot help. We do not develop or have Linux drivers.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zgb526642524** [comment]
Dear friends

   I implement the QCA7000/5 device driver in Allwinner V3S, which perfectly realizes the bridge from Ethernet to PLC.

Good luck！！！
